kind: Template
apiVersion: v1
metadata:
  name: rrror

parameters:
  - name: GATEWAY_SERVICE_ROOT
    value: "http://gateway-service.rrror.svc:8080"
    required: true
  - name: DB_SERVICE_HOST
    value: "http://db-service.rrror.svc:8080"
    required: true
  - name: CURRENT_ZONE
    value: "DEV | TEST"
    required: true


objects:
# ========================== DB-SERVICE ==========================
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: db-service-deployment
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      selector:
        deploymentconfig: db-service-deployment
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentconfig: db-service-deployment
        spec:
          containers:
            - image: "172.30.1.1:5000/rrror/db-service:1.0.0"
              imagePullPolicy: Always
              name: rrror-db
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: CURRENT_ZONE
                  value: ${CURRENT_ZONE}
    restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: db-service
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: db-service-deployment
      type: ClusterIP
# ========================== GATEWAY-SERVICE ==========================
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: gateway-service-deployment
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      selector:
        deploymentconfig: gateway-service-deployment
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentconfig: gateway-service-deployment
        spec:
          containers:
            - image: "172.30.1.1:5000/rrror/gateway:1.0.0"
              imagePullPolicy: Always
              name: rrror-gateway
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: CURRENT_ZONE
                  value: ${CURRENT_ZONE}
                - name: GATEWAY_SERVICE_ROOT
                  value: ${GATEWAY_SERVICE_ROOT}
                - name: DB_SERVICE_HOST
                  value: ${DB_SERVICE_HOST}
    restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: gateway-service
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: gateway-service-deployment
      type: ClusterIP

  - kind: Route
    apiVersion: v1
    metadata:
      name: gateway
      namespace: rrror
    spec:
      to:
        kind: Service
        name: gateway-service